### ISSUE TITLE
0.1.0 rc-2 bugs and suggestions

### ISSUE THREAD

**Issue by KevlarIRA** [TheMadDodger/Glory#187]
1.) Got an unknown error the log show up multiple times would be nice its error once known are coded with an identifier for future reference. 

2.) in perspective mode grid always seems to have a higher index than the objects by default making the grid always appear on top on the objects like a filter is there any way to lower its index?

3.) should allow materials to be compile without notifying the client to add both frag and vert shaders 

4.)Performance metrics tab when spawned, it off to the far right where a tiny section of the edge can be seen(only affected on the first time u spawn the window)

5.)Hovering over icons doesn't display a tooltip for its use, would be a nice accessibility feature if it did.

6.)Orthographic view has a very shallow front clipping clip and isnt adjustable (would be nice to be able to adjust front and back clipping planes)

7.)Models folder in the file browser is empty not sure it that's intended or not

8.) cant enable/disable objects in the inspector

9.) Could be nice to have a DoNotDestoryOnload section like in unity to have it automatically on the inspector tab where if u dragged a gameobject on to that section you could auto add code to the script to make that work

10) Cant remove additional device types if created in the input section of project settings

11) No clear way create cameras yet

12) when an exisiting or new project is opened the project browser hub should automatically close might confuse people when theres two seperate application icons visible 
![image](https://github.com/TheMadDodger/Glory/assets/114085861/0cc20fc9-bef0-493b-8c63-bbddb20ea0b1)

13) cant change fly/free view speed when navigating

14) if a scene is saved and nothing else in the project as then altered before that it should save the project automatically to or else there will still be a asterisk on the title and a warning when u try to quit

**Comment by TheMadDodger** [comment]
@KevlarIRA 
> 1.) Got an unknown error the log show up multiple times would be nice its error once known are coded with an identifier for future reference.
Unfortunately this is a weird edge case error from opengl which ive tried many times to solve, but due to the nature of how the engine works and bc opengl likes to keep its actual errors a secret, I have not been able to solve it, the good news is that it does not affect anything, everything should remain working, if it does affect something then its likely due to a missing or not compilable shader

> 3.) should allow materials to be compile without notifying the client to add both frag and vert shaders
Problem is opengl will simply say no if you dont add both shaders, but a warning telling you the material is incomplete should definitely be added

> 4.)Performance metrics tab when spawned, it off to the far right where a tiny section of the edge can be seen(only affected on the first time u spawn the window)
You mean the text is cut off?

> 7.)Models folder in the file browser is empty not sure it that's intended or not
Do you mean the Modules folder? It should contain folders for each module that is in use, some should have assets you can browse through there as well, but it does not allow editing/deleting or importing anything in that folder

> 9.) Could be nice to have a DoNotDestoryOnload section like in unity to have it automatically on the inspector tab where if u dragged a gameobject on to that section you could auto add code to the script to make that work
I agree though I find the way Unity does this rather finnicky, I want to come up with my own solution for this

> 10. Cant remove additional device types if created in the input section of project settings
There should be a - button at the far right edge, though iirc it can be hard to click it, will fix this

> 11. No clear way create cameras yet
A camera is also a component, you add it to any object in your scene, do you mean you would like a faster way to add a camera like having an option in the right click menu->Create/Camera ?

**Comment by KevlarIRA** [comment]
for 4.) the whole window for the performance is way off to the right only a slight bit of the left side was visible so i was able to drag it out and dock it properly it would happened once the first time i opened it idk if it occurs whenever u first open a new project or the first time using that specific editor version

11.) we i think just having a right click menu to create camera would be better since its a more staple common object than others 

10.) i do see the - button but when i clicked on it, it just showed the dropdown list for the devices again instead of removing the current one idk if this is fixed in rc4 yet
